CREATE DATABASE IF NOT EXISTS supermercado;

USE supermercado;

CREATE TABLE IF NOT EXISTS CIUDAD (
    ID_Ciudad INTEGER PRIMARY KEY AUTO_INCREMENT,
    Nombre_Ciudad VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS CATEGORIA (
    Id_Categoria INTEGER PRIMARY KEY AUTO_INCREMENT,
    Nombre_Categoria VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS PROVEEDOR (
    ID_Proveedor INTEGER PRIMARY KEY AUTO_INCREMENT,
    Nombre VARCHAR(50) NOT NULL,
    Telefono VARCHAR(15) NOT NULL,
    Email VARCHAR(60) NOT NULL UNIQUE,
    Direccion VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS CLIENTE (
    ID_Cliente INTEGER PRIMARY KEY  UNIQUE, 
    Nombre_cliente VARCHAR(60) NOT NULL,
    Telefono VARCHAR(15) NOT NULL,
    Email VARCHAR(60) NOT NULL UNIQUE
    );

CREATE TABLE IF NOT EXISTS MEDIO_PAGO (
    ID_Pago INTEGER PRIMARY KEY AUTO_INCREMENT,
    Tipo_Pago VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUCTO (
    Id_producto INTEGER PRIMARY KEY AUTO_INCREMENT,
    Nombre_Producto VARCHAR(50) NOT NULL,
    Precio_producto FLOAT NOT NULL,
    stock INTEGER NOT NULL,
    ID_categoria INTEGER NOT NULL,
    ID_Proveedor INTEGER NOT NULL,
    FOREIGN KEY (ID_categoria) REFERENCES CATEGORIA(Id_Categoria),
    FOREIGN KEY (ID_Proveedor) REFERENCES PROVEEDOR(ID_Proveedor)
);

CREATE TABLE IF NOT EXISTS MARCA (
    ID_Marca INTEGER PRIMARY KEY AUTO_INCREMENT,
    Nombre VARCHAR(50) NOT NULL,
    Descripcion VARCHAR(80) NOT NULL
);

CREATE TABLE IF NOT EXISTS SUCURSAL (
    Id_Sucursal INTEGER PRIMARY KEY AUTO_INCREMENT,
    Nombre_sucursal VARCHAR(50) NOT NULL,
    direccion_sucursal VARCHAR(50) NOT NULL,
    ID_Ciudad INTEGER NOT NULL,
    FOREIGN KEY (ID_Ciudad) REFERENCES CIUDAD(ID_Ciudad)
);

CREATE TABLE IF NOT EXISTS EMPLEADO (
    ID_Empleado INTEGER PRIMARY KEY UNIQUE,
    Nombre_empleado VARCHAR(60) NOT NULL,
    Telefono VARCHAR(15) NOT NULL,
    Email VARCHAR(60) NOT NULL UNIQUE,
    Direccion VARCHAR(50) NOT NULL,
    ID_Sucursal INTEGER NOT NULL,
    FOREIGN KEY (ID_Sucursal) REFERENCES SUCURSAL(Id_Sucursal)
);

CREATE TABLE IF NOT EXISTS FACTURA (
    ID_Factura INTEGER PRIMARY KEY AUTO_INCREMENT,
    Fecha_Factura DATETIME NOT NULL,
    ID_Pago INTEGER NOT NULL,
    ID_Sucursal INTEGER NOT NULL,
    ID_Cliente INTEGER NOT NULL,
    ID_Empleado INTEGER NOT NULL,
    FOREIGN KEY (ID_Pago) REFERENCES MEDIO_PAGO(ID_Pago),
    FOREIGN KEY (ID_Sucursal) REFERENCES SUCURSAL(Id_Sucursal),
    FOREIGN KEY (ID_Cliente) REFERENCES CLIENTE(ID_Cliente),
    FOREIGN KEY (ID_Empleado) REFERENCES EMPLEADO(ID_Empleado)
);

CREATE TABLE IF NOT EXISTS INVENTARIO (
    ID_Inventario INTEGER PRIMARY KEY AUTO_INCREMENT,
    Cantidad INTEGER NOT NULL,
    ID_Sucursal INTEGER NOT NULL,
    ID_Producto INTEGER NOT NULL,
    FOREIGN KEY (ID_Sucursal) REFERENCES SUCURSAL(Id_Sucursal),
    FOREIGN KEY (ID_Producto) REFERENCES PRODUCTO(Id_producto)
);

CREATE TABLE IF NOT EXISTS PROMOCION (
    ID_Promocion INTEGER PRIMARY KEY AUTO_INCREMENT,
    Descuento FLOAT NOT NULL,
    Fecha_Inicio DATE NOT NULL,
    Fecha_Fin DATE NOT NULL,
    ID_Producto INT NOT NULL,
    FOREIGN KEY (ID_Producto) REFERENCES PRODUCTO(Id_producto)
);

CREATE TABLE IF NOT EXISTS PRODUCTOS_PROMOCION (
    ID_Promo INTEGER PRIMARY KEY AUTO_INCREMENT,
    Detalle_Promo VARCHAR(50) NOT NULL,
    ID_Promocion INTEGER NOT NULL,
    ID_Producto INTEGER NOT NULL,
    FOREIGN KEY (ID_Producto) REFERENCES PRODUCTO(Id_producto),
    FOREIGN KEY (ID_Promocion) REFERENCES PROMOCION(ID_Promocion)
);

CREATE TABLE IF NOT EXISTS Pedido_Proveedor (
    ID_Pedido INTEGER PRIMARY KEY AUTO_INCREMENT,
    Cantidad INTEGER NOT NULL,
    Fecha_Pedido DATETIME NOT NULL,
    ID_Proveedor INTEGER NOT NULL,
    ID_Producto INTEGER NOT NULL,
    ID_Sucursal INTEGER NOT NULL,
    FOREIGN KEY (ID_Proveedor) REFERENCES PROVEEDOR(ID_Proveedor),
    FOREIGN KEY (ID_Producto) REFERENCES PRODUCTO(Id_producto),
    FOREIGN KEY (ID_Sucursal) REFERENCES SUCURSAL(Id_Sucursal)
);

CREATE TABLE IF NOT EXISTS VENTA_PRODUCTO (
    ID_Venta_Producto INTEGER PRIMARY KEY AUTO_INCREMENT,
    Cantidad INTEGER NOT NULL,
    ID_Factura INTEGER NOT NULL,
    ID_Producto INTEGER NOT NULL,
    FOREIGN KEY (ID_Factura) REFERENCES FACTURA(ID_Factura),
    FOREIGN KEY (ID_Producto) REFERENCES PRODUCTO(Id_producto)
);